// profile sce_vp_psp2

uniform float4x4 u_WorldMatrix;
uniform float3 u_LightDirection;

void main(
	float4 a_position,
	float2 a_texCoord,
	float3 a_normal,
	float2 out v_texCoord : TEXCOORD0,
	float4 out v_DiffuseLight : TEXCOORD1,
	float4 out gl_Position : POSITION
) {
	gl_Position = mul(a_position, u_WorldMatrix);
	v_texCoord = a_texCoord;
	v_DiffuseLight.rgb = float3(max(dot(a_normal, u_LightDirection), 0.0));
	v_DiffuseLight.a = 1.0;
}
